connections:
  name:
    url: ws://localhost:5678
    reconnection_atempts: something
    other: params

  name1:
    url: ws://localhost:5678
    reconnection_atempts: something
    other: params

  name2:
    url: ws://localhost:5678
    reconnection_atempts: something
    other: params
